[package]
name = "pneuma-stealth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rand.workspace = true
ring.workspace = true
serde.workspace = true
